DigitalX/Controllers/CartController.cs
using DigitalX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalX.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository iProductRepository = new ProductRepository();
        // GET: Cart
        public ActionResult Index()
        {
            return View("Index");
        }


        public ActionResult Buy(int id)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item()
                {
                    product = iProductRepository.find(id),
                    quantity = 1
                });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExits(id);
                if (index == -1)
                {
                    cart.Add(new Item()
                    {
                        product = iProductRepository.find(id),
                        quantity = 1
                    });
                }
                else
                {
                    cart[index].quantity = cart[index].quantity + 1;
                }
                Session["cart"] = cart;
            }
            return View("Index");
        }

        private int isExits(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].product.ProductID == id)
                    return i;
            return -1;
        }

        public ActionResult Delete(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(id);
            Session["cart"] = cart;
            return View("Index");
        }
    }
}

DigitalX/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalX.Controllers
{
    public class HomeController : Controller
    {
        GatDataServiceReference.GetDataServiceClient db = new GatDataServiceReference.GetDataServiceClient();
        public ActionResult Index()
        {
            var top = db.ProductGetTop(8);
            return View(top);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

DigitalX/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalX.Controllers
{
    public class ProductsController : Controller
    {
        GatDataServiceReference.GetDataServiceClient db = new GatDataServiceReference.GetDataServiceClient();
        // GET: Products
        public ActionResult Index()
        {
            var pro = db.ProductGetAll();
            return View(pro);
        }

        public ActionResult Details(int? id)
        {
            var pro = db.ProductGetDetails(id);
            return View(pro);
        }
    }
}

DigitalX/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section id="content">

    <div class="content-wrap">

        <div class="container clearfix">

            <div class="col_full">

                <div class="heading-block center nobottomborder">
                    <h2>About This <span>DigitalX</span> Project</h2>
                    <span>This section is about how I designed &amp; built this DigitalX Application.</span>
                </div>

                <div class="fslider" data-pagi="false" data-animation="fade">
                    <div class="flexslider">
                        <div class="slider-wrap">
                            <div class="slide"><a href="#"><img src="@Url.Content("~/Content/Images/rockrecords.jpg")" alt="About Image"></a></div>
                        </div>
                    </div>
                </div>

            </div>
            <br />

            <div class="clear"></div>

            <div class="promo promo-light bottommargin">
                <h3>Contact me today at <span>+91.22.57412541</span> or Email me at <span>sara.elizabeth.lowrie.com</span></h3>
            </div>

            <div class="clear"></div>
            <br />
            <br />

            <div class="col_one_third">

                <div class="heading-block fancy-title nobottomborder title-bottom-border">
                    <h4>Project <span>Plan</span></h4>
                </div>

                <p>
                    To start this project I needed to do a lot of research about Wcf Service &amp; how it interacts with Entity Framework &amp; Mvc.
                    I started with the front end so had a look at some modern online shopping sites &amp; the latest web design trends before I made it.
                    Next I did the backend product sections of the project and checked functionality. Third I did the checkout and then the registration &amp; login.
                    Last I did the create and view order section.
                </p>

            </div>

            <div class="col_one_third">

                <div class="heading-block fancy-title nobottomborder title-bottom-border">
                    <h4>Special <span>Techniques</span></h4>
                </div>

                <p>
                    For the header I found that non rectangular headers are becoming a trend so I used SVG to draw the uneven lines &amp; shadow.
                    I used a picture of headphones from the internet &amp; photoshop to make a logo that I think fits the DigitalX brand.
                </p>

            </div>

            <div class="col_one_third col_last">

                <div class="heading-block fancy-title nobottomborder title-bottom-border">
                    <h4>DigitalX <span>Function</span></h4>
                </div>

                <p>
                    DigitalX is an MVC online shopping application designed to so users can browse &amp; purchase listed products.
                    The app makes customers register to order products they have put in the cart but no memebership is required for browsing the products.
                </p>

            </div>

        </div>

    </div>

</section>

DigitalX/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<div class="heading-block center nobottomborder">
    <h2><span>Contact</span> Details</h2>
</div>

<section id="content">

    <div class="content-wrap">

        <div class="container clearfix">

            <div class="clear"></div>

            <div class="promo promo-light bottommargin">
                <h3>Contact me today at <span>+(64)021 130 1800</span> or Email me at <span>sara.elizabeth.lowrie.com</span></h3>
            </div>

            <div class="clear"></div>

        </div>

   </div>

</section>

DigitalX/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">

            <div class="heading-block center nobottomborder">
                <h2><span style="color: orange;">Top</span> Products</h2>
                <span>Check out some of the most popular DigitalX products below.</span>
            </div>

            <div id="shop" class="shop grid-container clearfix" data-layout="fitRows">
                @foreach (var item in Model)
                {
                    <div class="product clearfix">
                        <div class="product-image">
                            <a href="@Url.Action("Details", "Products", new { id = item.ProductID })">
                                <img src="data:image/png;base64,@Convert.ToBase64String(item.Picture, Base64FormattingOptions.None)" alt="Image" />
                            </a>
                        </div>
                        <br />
                        <div class="product-title"><h3>@item.ProductName</h3></div>
                        <div class="product-price">$@item.Price</div>
                        <a href="@Url.Action("Buy", "Cart", new { id = item.ProductID })" class="button button-border button-rounded button-fill button-aqua">
                            <span>Add to Cart</span>
                        </a>
                    </div>
                    @*<br />
                    <br />*@
                }
            </div>
        </div>
    </div>
</section>